### ISSUE TITLE
Actions toolbar isn't visible in Kagi Assistant on small devices

### ISSUE THREAD

**Issue by CometDog** [jcrabapple/kagi-catppuccin-light-dark#19]
The CSS here:

```css
@media all and (max-device-width:766px){
...
.chat_bubble .actions .left{
  display:none!important
}
...
```

Is causing the toolbar on Assistant to be hidden on small devices (iPhone 13 Mini).

Is there a purpose to hiding actions at this media size? Is actions used elsewhere that you are trying to suppress or is it maybe just something that got lost in the sea of CSS?

This is the toolbar being hidden in Assistant in question:

![Image](https://github.com/user-attachments/assets/3806b52f-3bea-48e2-af2b-44ab75339127)

Insert into yourself an image of my Assistant without this toolbar at the bottom of the AI response and that's the bug
